### ISSUE TITLE
PHP warnings in PluginSystem

### ISSUE THREAD

**Issue by tmccormi** [LibreEHR/LibreEHR#180]
Please clean up.

[Fri Sep 16 14:49:11.261190 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice: Undefined index: plugins_started in C:\xampp\htdocs\LibreEHR\library\pluginsystem\PluginSystem.php on line 192, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1
[Fri Sep 16 14:49:11.261190 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice: Undefined variable: ret in C:\xampp\htdocs\LibreEHR\library\pluginsystem\PluginSystem.php on line 203, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1
[Fri Sep 16 14:49:11.286806 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice: Use of undefined constant authUserID - assumed 'authUserID' in

**Comment by teryhill** [comment]
Did you try clearing the smarty cache

**Comment by samlikins** [comment]
@kchapple,

I also ran across the following error when logging into the system:

`Warning: Cannot modify header information - headers already sent by (output started at .../library/pluginsystem/PluginSystem.php:203) in .../interface/main/tabs/redirect.php on line 25`

This is a fresh `master` run, not seeming to affect others, but it seems to be a serious issue caused by the sending of headers, then content, then headers again.  The content may just be a blank line, as is commonly the issue.

**Comment by aethelwulffe** [comment]
Got rid of the error (just to verify cause and effect) for $actions by initializing it in the helper include.  $ret failed to respond to that tactic, and I am pretty sure there are PHP 7 thingies where type declarations for return values may be part of why I can't just shut the error up.

**Comment by aethelwulffe** [comment]
pull request merged from kchapple.
